# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `main_hec_nov_2025`")
spark.sql("USE SCHEMA `axel_richier`")

# COMMAND ----------

# MAGIC %sh cat /Volumes/main_hec_nov_2025/telemetry/raw/events/hr/samples/2025-10-16_205740.json

# COMMAND ----------

df = spark.read.option('primitivesAsString',True).json('/Volumes/main_hec_nov_2025/telemetry/raw/events/hr/samples/2025-10-16_205740.json')

# COMMAND ----------

display(df)
